### PR TITLE
Tweak CodeMirror hint styles

### PR DESCRIPTION
**Pull request by Matsuuu**
Modifying the code hint styles according to discussion in https://github.com/lit/lit.dev/pull/689

- Remove padding from hintlist
- Move removed padding to items
- Remove border-radius from hintlist
- Inherit font

Subjects up for discussion:

- Should we remove the box shadow from the completion items list? Does this affect visual clarity?
- What font weight should the completion items be?

### CODE REVIEW

**Review by AndrewJakubowicz — CHANGES_REQUESTED** [review]
Thank you for making this PR!!!

I'd opt-out of having the `bold` option [here](https://github.com/google/playground-elements/pull/263/files#diff-1fc8310580b76754326514d9c01cc9731ffeafe9a1ef20c5e5fb496532ae4a41R422), as in configurator only `monospace` works with bold. The other font selections look the same.

And I'm happy to keep the shadow as well.

Otherwise this LGTM! Tested by randomly changing colors and things in the configurator.
Thank you so much!

**Comment by Matsuuu** [comment]
Great catches here too! Did the necessary style tweaks

**Review by AndrewJakubowicz — CHANGES_REQUESTED** [review]
Brilliant!

The only two last things that come to mind (that maybe we don't need to address):

1. Maybe we make a new CSS custom property for the [CodeMirror-hint-active selector](https://github.com/google/playground-elements/pull/263/files#diff-1fc8310580b76754326514d9c01cc9731ffeafe9a1ef20c5e5fb496532ae4a41R409-R412), instead of the filter to allow more control on the active color.

2. Responsiveness on narrow devices.

On Stackblitz there is some space between the hint and viewport: 
Screen Shot 2022-02-15 at 12 31 52 PM
Whilst currently on the preview lit.dev branch, the hint box touches the viewport edge:
Screen Shot 2022-02-15 at 12 33 25 PM

**Comment by Matsuuu** [comment]
Heya,

I think the color customization is quite good as is as it is attached to the theming, and is inherited from the theme itself, instead of other custom properties.

As for the responsiveness, I added a small `min` css function to make the completion item list a bit more responsive on smaller screens. I don't  know if we should put too much effort into supporting mobile size screens due to them not being really the use case for a code editor in my opinion

**Review by AndrewJakubowicz — APPROVED** [review]
That makes sense. Changes LGTM.

I can make another pre-release of playground elements and try on lit.dev.
Thank you!

**Review by aomarks — APPROVED** [review]

**Pull request merged**
